### ISSUE TITLE
[Sugestion] Shutdown computer after dropping all cards

### ISSUE THREAD

**Issue by GabrielDuarteM** [jshackles/idle_master#123]
i have a sugestion for you, sometimes when i buy games i let idlemaster drop all cards, and usually i do this at night, or when i'm not using the computer. So it would be nice if i had the possibility to turn off my computer automatically when idlemaster finish idling all cards...

**Comment by Efreak** [comment]
This would be a useful feature. :+1:

In the meantime:
1. `shutdown.exe -s -t 3600` from the run menu will shut down your computer in an hour. You can also specify a time if you want, instead of a timer. This is a command built into windows (most *nixes and osx should have `shutdown -P +minutes` or `shutdown -P $TIME`)
2. If you want something a little more powerful, look at [DShutdown](http://dimio.altervista.org/eng/).
