### ISSUE TITLE
Build and error

### ISSUE THREAD

**Issue by KriBetko** [jshackles/idle_master#132]
I downloaded the source IdleMaster and run it in Visual Studio. But faced with an error in the building of the project.
I launched building and told me about the lack of reference to Steamworks.NET. Ok, I downloaded Steamworks.NET source, built it for Windows x86 and added to the reference. and I rename the Steamworks.NET.dll in CSteamworks.dll and put it in the Resources folder. Then I started building again IdleMaster and got an error "he 'SignFile' task was not given a value for the required parameter 'CertificateThumbprint' ". How to solve it? I have no idea.
And yet, what kind of file "code signing.pfx" is not in the project? I believe that it is the cause of the problem.

**Comment by jshackles** [comment]
The code signing certificate is used to verify the program's authenticity and is thus not included in the source.  Visual Studio uses this certificate for it's build process so that when a new version is uploaded to the server, the application will check that the certificate thumbprint matches before updating the application.  This is done to make sure that some malware author can't compromise our web server and upload their payload to be distributed to everyone running Idle Master.

You should be able to bypass any reference to the code signing certificate by opening the application properties and selecting "Signing", then uncheck "Sign the ClickOnce manifests".  You should then also be able to remove the reference to the code signing.pfx file using the Solution Explorer.

**Comment by KriBetko** [comment]
Working! Thank you very much for your reply and for your program!
If I translate or other modifying a program without your certificate, they will schitatne illegal? I do not want to create problems you and yourself.

**Comment by jshackles** [comment]
No that shouldn't be a problem at all.  :+1:  It just means you (obviously) won't be able to redistribute it from www.SteamIdleMaster.com is all.
