### ISSUE TITLE
[Question] Why not idle all games at the same time?

### ISSUE THREAD

**Issue by RockyTV** [jshackles/idle_master#167]
Me and my friend have been discussing this for a while, why does IdleMaster idle up to 5-6 games at the same time until they reach 2 hours, and then idle each gime individually?

Is it because Steam won't award cards to you if you're on 2 games at the same time?

**Comment by jshackles** [comment]
Every game launched reduces the rate that cards are dropped.  Having more than 4 games open at once seems to set the drop rate to 0 (no cards given, regardless of how long the games are idle).

The reason that Idle Master idles multiple games at once in the beginning is due to a recent change made by Valve in regards to their refund policy.  Games are not "eligible" to drop cards now until after they have at least two hours of play time.  Steam will also only recognize up to 30 games idle at a time.   Thus Idle Master will attempt to idle as many games as possible (in batches of 30) up to the two hour mark so that they become eligible, then will begin idling games individually to maximize efficiency.

**Comment by RockyTV** [comment]
Thank you very much!
