### ISSUE TITLE
Idle Master is not working.

### ISSUE THREAD

**Issue by primmughal** [jshackles/idle_master#229]
Idle master is not working. It creates a notepad error file when I run it. Errors are increasing till I close the program. 
![idle master](https://cloud.githubusercontent.com/assets/22270593/18613418/ee25faf2-7d93-11e6-8ac7-9566053cc48a.jpg)

**Comment by fdornak** [comment]
Would you mind to post that error.txt file here? Did Idle master work in the past on this machine ?

**Comment by primmughal** [comment]
Yes it is working. I am using it since three days. Error image
![idle master errors](https://cloud.githubusercontent.com/assets/22270593/18613566/f0896ae2-7d96-11e6-9511-07d830504027.jpg)
 is attached.

**Comment by fdornak** [comment]
This issue is caused by corrupted IdleMaster.exe.config (4KB). To fix this you can:

1. Reinstall Idle Master (recommended)
Control Panel - Programs and Features - IdleMaster - Uninstall/Change
Download installer from [here](http://www.steamidlemaster.com/) and run it

2. Replace corrupted config file
Download [this file](https://github.com/jshackles/idle_master/blob/master/Source/IdleMaster/app.config)
Rename it as IdleMaster.exe.config
Paste it into your folder with IdleMaster (Replace)


The reason why this happened might be:

1. You modified .config file
2. System was forced to shut down in the middle of writing into this file.
3. Hard drive problem

**Comment by primmughal** [comment]
Thanks a lot. My issue has been resolve by replacing idlemaster.exe configuration file.

**Comment by fdornak** [comment]
I am glad I coud help. As a solved problem, please mark this issue as closed.

**Comment by primmughal** [comment]
![idle mater is not working](https://cloud.githubusercontent.com/assets/22270593/18789418/5fbabb92-81c4-11e6-811f-85b571679276.jpg)

**Comment by primmughal** [comment]
![error](https://cloud.githubusercontent.com/assets/22270593/18789428/6c1b58ba-81c4-11e6-864f-d34693ee8488.jpg)
