### ISSUE TITLE
Staying logged in

### ISSUE THREAD

**Issue by xur86x** [jshackles/idle_master#95]
There should be an option to stay logged in into Steam.

**Comment by jshackles** [comment]
The program saves the information it needs in your local settings file, so by default you shouldn't have to sign in to Steam each time.  So I'm not sure if I understand your suggestion.

**Comment by xur86x** [comment]
Somehow it is not saving it for me. I always have to log in again after restarting it. I've tried running it with admin rights too.

**Comment by jshackles** [comment]
Can you try downloading the portable version from www.SteamIdleMaster.com and extracting it somewhere your user has full access to (such as your desktop) and see if the you're still having the same problem.  It sounds like this could be a permissions issue on your file system.

**Comment by xur86x** [comment]
Apparently it was the permissions causing this. I'll uninstall the normal version and use this instead, thanks. I don't know if this is the case, but I remember you mentioned that the portable version has no automatic update, why is that?

**Comment by jshackles** [comment]
Glad to hear it's working as needed now.  The reason the portable version doesn't update automatically was actually by design by very popular request.  A lot of people were hesitant to use the program initially because it updated automatically and they were worried that I would try to sneak in some spyware or malware.

I'll be updating the zip file on the website each time a new version is released, so keep your eyes on the official group for release announcements

http://steamcommunity.com/groups/idlemastery

**Comment by xur86x** [comment]
It surprises me, that there are people who think that the maker of Enhanced Steam would do such a thing. Your reputation would be ruined instantly.
I also found out why the normal version wouldn't save my information. The folder was set to read-only.
Could you maybe implement an update notification in the portable version? The program would check if there is a newer version at each run and notifies the user if there is a new version.

**Comment by xur86x** [comment]
Another tip for you that might improve the trust in your software: Some virus scanners see the program as malware, which is probably the reason many users were so sceptical.
I already reported it as a false alert, maybe it helps.
